### ISSUE TITLE
Arc/edge reduction, how to force they keep split?

### ISSUE THREAD

**Issue by skinkie** [RoutingKit/RoutingKit#11]
Currently the processing of the pbf input results int arcs that are split based on topology (as one would expect). But from my own implementation to implement the reduction, the code is rather complex and so is yours.

What I would like to achieve that for some nodes I can deeply trust on a split behavior, and would be able to do so by a user defined key/value pair from the OSM Tags. I assume that I get my desired behavior via `modelling_node_is_routing_node`. My use case would be tram/rail stops.

It is a bit vague to me why this suggest that there is a lookup;
https://github.com/RoutingKit/RoutingKit/blob/master/src/osm_graph_builder.cpp#L25

But the function is always initialised with nullptr.
```cpp
    auto mapping = load_osm_id_mapping_from_pbf(
        pbf_file,
        nullptr,
        [&](uint64_t osm_way_id, const TagMap&tags){
            return is_osm_way_used_by_cars(osm_way_id, tags, log_message);
        },
        log_message
    );
```

**Comment by ben-strasser** [comment]
Hi,

yes, you can pass a callback that should return true for nodes that should be routing nodes even though they are not intersection or endpoints. The signature is bool(uint64_t, const TagMap&), i.e., you get the osm ID and the tags. The routing node ID is not yet known at this point and therefore not a parameter. Now that I look at the code, I'm wondering myself why the latitudes and longitudes are not parameters. I think the information is already known at that point...

nullptr is semantically equivalent to always returning false but is faster because the tag map and the latitudes and longitudes of the nodes are not decoded from the PBF.

Best Regards
Ben Straser

**Comment by skinkie** [comment]
Thanks this will help!
