### ISSUE TITLE
Warning: OSM way 5302778 has an unrecognized value of "unposted" for its "maxspeed" tag

### ISSUE THREAD

**Issue by xydinesh** [RoutingKit/RoutingKit#41]
I have tried smaller pbf files with main.cpp given in the example and it works. However I'm getting an error when I try to read pbf file for north-america from geofabrik.

http://download.geofabrik.de/north-america-latest.osm.pbf

Here is my error:

terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call

and it is coming from,

auto graph = simple_load_osm_car_routing_graph_from_pbf("/data/north-america-latest.osm.pbf");

appreciate any pointers on fixing this.

**Comment by xydinesh** [comment]
Actually error comes from here

https://github.com/RoutingKit/RoutingKit/blob/master/src/osm_profile.cpp#L356

```gdb
#7  0x00000000004373f0 in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (
    __args#0="Warning: OSM way 5302778 has an unrecognized value of \"unposted\" for its \"maxspeed\" tag.", this=0x7fffffffc040)
    at /usr/include/c++/5/functional:2266
#8  RoutingKit::(anonymous namespace)::parse_maxspeed_value(uint64_t, const char *, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>) (osm_way_id=osm_way_id@entry=5302778, maxspeed=<optimized out>, maxspeed@entry=0x7fffffffc060 "unposted",
    log_message=...) at src/osm_profile.cpp:356
```

**Comment by ben-strasser** [comment]
Hi,

thanks for the bug report. I think I see where the problem is in lines 
286, 352, 356 and 380. log_message can be nullptr. Therefore the call to 
log_message needs to be protected using an if(log_message) log_message(...);

Could you please verify that this work? If so, I'll patch the master 
accordingly

Best Regards
Ben Strasser

**Comment by xydinesh** [comment]
Yes it is related to log_message. I provided empty log message function to simple_load_osm_car_routing_graph_from_pbf and it worked. Let me verify changing locations you mentioned too.

**Comment by ben-strasser** [comment]
Hi,

can confirm crash. It happens when logging is deactivated because a few log_message calls were not protected. I pushed a patch that adds the missing checks. It should work now.

The log message itself is correct. It tells you that
https://www.openstreetmap.org/way/5302778
has a "max_speed" tag with a value of "unposted". According to the wiki
https://wiki.openstreetmap.org/wiki/Key:maxspeed
this is not a valid value. This is thus a tagging error in OSM. 

Are there many roads in the USA with this value? If so, I can add a check for it. If there are only few roads, please fix the tags.
 
Best Regards
Ben Strasser

**Comment by xydinesh** [comment]
Thanks ! Actually there are bunch of invalid tags for maxspeed in north-america file. I don't think it's worth to fix in the code. I want to say about 100 of different invalid cases in 8GB file.  Thanks for fast feedback. We can close this issue.

**Comment by ben-strasser** [comment]
The code now handles unposted-maxspeed tags as no maxspeed tag
